name: .NET Core Desktop

on:
    push:
        branches: ["staging"]

jobs:
    build:
        runs-on: windows-latest

        env:
            Solution_Name: HouseRentingSystem.sln
            Test_Project_Path: HouseRentingSystem.Tests\HouseRentingSystem.Tests.csproj

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 6.0.x

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v2

            - name: Restore dependencies
              run: dotnet restore

            - name: Build solution
              run: dotnet build

            - name: Execute unit tests
              run: dotnet test ${{ env.Test_Project_Path }}
