name: .NET Core Desktop

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: windows-latest 
    
    env:
      Solution_Name: HouseRentingSystem.sln                                                              # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: HouseRentingSystem.UnitTests\HouseRentingSystem.UnitTests.csproj                # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

